### ISSUE TITLE
xsqlserversetup

### ISSUE THREAD

**Issue by Bjorn80** [PowerShell/xSQLServer#131]
Hi

What are the input options for SecurityMode ? 
SecurityMode = "SQL" did not work.
brgs

bJørn

**Comment by Bjorn80** [comment]
I am trying to set mixed mode authentication.

Brgs

Bjørn

**Comment by johlju** [comment]
Looking at the code, if `Features` contains `'SQLENGINE'`, `SecurityMode` is set to `'SQL'` and `SAPwd` is set to a password, it seems is could work. I say could, because I'm not sure, since you have a issue with this. :)
```
Features = 'SQLENGINE'
SecurityMode = 'SQL'
SAPwd = 'P@ssw0rd'
```

What does you output look like? In the file `%Program Files%\Microsoft SQL Server\<version>\Setup Bootstrap\Log\Summary.txt`, see the `User Input Settings:` section. Does it add `'SQL'` to the `SECURITYMODE` command-line parameter?

**Comment by johlju** [comment]
@Bjorn80 have you solved this? Or can we help you in anyway? Really interest if this is a bug in the resource.

If we don't hear from you in a few days I think we can assume the matter is solved and close this issue. If it is not solved you can open it up at anytime.

**Comment by Bjorn80** [comment]
Hi johlju, I tried this xsqlserversetup resource in my DSC infancy. When I couldn't get it to work I switched to the xSQLServer module instead. I did not come back to test the xsqlserversetup again. So I can not verify that there is a bug. Most likely I probably did something wrong there:-)
brgs.

Bjørn
