### ISSUE TITLE
Difference between Resource Name and Test Name

### ISSUE THREAD

**Issue by luigilink** [PowerShell/xSQLServer#134]
In DSCResources folder and in Tests\Unit folder, we find the name that starts with MSFT... or xSQL... 
Can we have the same start name in all folders ?

I also noticed that sometimes, we have MSFT_xSQLServer... or MSFT_xSQL...

PR #136

**Comment by johlju** [comment]
The once with MSFT was developed by Microsoft employees (contributors) and the ones without was developed my community contributors. Like myself. The exception to this is when I continued working on a resource created my a Microsoft employee, which I left names MSFT. 

If this is not something that should be enforced we could remove MSFT altogether I think. 

@kwirkykat what do you say about the naming convention? I haven't read that somewhere in any .md I think. Or have I missed it?

**Comment by luigilink** [comment]
I don't know either if there is naming convention, but I think it's a nice to have.
I agree with you, we could remove MSFT, I have to change my previous commit.
Maybe we can discuss for a global naming convention for all DSC resources

**Comment by johlju** [comment]
Let's see what @kwirkykat say. Or maybe @mbreakey3 can give us some guidance on this too.

**Comment by kwirkykat** [comment]
@johlju @luigilink All mof-based resources (with Get/Set/Test-TargetResource and a schema.mof file) should start with MSFT_ regardless of who originally wrote them because they are now part of a Microsoft project. The MSFT_ is apparently a convention for mof-based resources to designate what company the resource comes from.

@mbreakey3 and I didn't learn about this rule/convention until last week. I don't know if other maintainers know about it either, so that's probably why resources were added here without the MSFT_.

Any composite resources (a confiugration with a .psd1 file) **cannot** start with MSFT_ as they will not work unless the name of the files matches the name of the resource.

Class-based resources are still up-in-the-air for the DSC Resource Kit, but I don't think you have any here anyways.

**Comment by johlju** [comment]
Thank for the quick answer @kwirkykat, then this PR that was submitted is all good @luigilink. 

We probably should get this new information into the contribution.md, are you on that @kwirkykat? Or shall we submit an issue into DscResources?

**Comment by kwirkykat** [comment]
@johlju I got it

**Comment by kwirkykat** [comment]
Fixed by PR #136
