### ISSUE TITLE
xSQLAOGroupEnsure: Hard coded to use impersonation, thus cannot not use 'PsDscRunAsCredential'

### ISSUE THREAD

**Issue by aultt** [PowerShell/xSQLServer#141]
Resource xSQLAOGroupEnsure is referenced as xSqlServerAoJoin in the readme.  Readme should be updated to reflect the correct resource.
Resource xSQLAOGroupEnsure in the readme states SetupCredential should be $Null for Windows Authentication which is incorrect as it is a mandatory parameter.

**Comment by johlju** [comment]
You are right. When adding credentials to the `SetupCredential` it's impersonate the login, so we should change this so that it can use the credential passed in `PsDscRunAsCredential`. Making the SetupCredential not mandatory and leave the parameter out from the config will make the `Connect-SQL` function to connect using as the current user, which should be the user in `PsDscRunAsCredential`. Or I'm I think about this wrong?

**Comment by johlju** [comment]
Closing this issue since this resource is deprecated.
