### ISSUE TITLE
Get-TargetResource doen't work for SQL server 2016

### ISSUE THREAD

**Issue by nitinbps** [PowerShell/xSQLServer#142]
Installation of the features for SQL server 2016 was done successfully but Test-TargetResource returns false. Test-TargetResource internally calls Get-TargetResource which doesn't return the list of features installed.

**Comment by Indhukrishna** [comment]
The Feature list returned by Get-TargetResource is empty

**Comment by johlju** [comment]
I haven't seen this when I deployed SQL 2016. In what scenario do you get this error?
And could you please verify if the code in PR #132 fixes this issue?

I can't reproduce it when using the code from PR #132, neither using the dev branch. I always get a feature list back (which in my case only contains 'SQLENGINE'). But I might be testing with other parameters.

**Comment by joshan1120** [comment]
I also have this issue with SQL 2014. I used the code from #132 

My feature list is as follows:
SqlInstallFeatures = 'SQLENGINE,FULLTEXT,SSMS,ADV_SSMS,IS,CONN,BC'

**Comment by forensicsguy20012004** [comment]
@joshan1120 Can you try the install using something like this: $Features = "SQLENGINE,IS,SSMS,ADV_SSMS" I had problems with the "CONN,BC" feature set...once I removed these...the install went through just fine.

**Comment by joshan1120** [comment]
It does for me also, but I need those features for my requirements.

**Comment by forensicsguy20012004** [comment]
@joshan1120 If you look at this issue: Module does not support installed features BC, CONN, and BIDS #69 ... I do believe this is kind along the same issue you are talking about...I could be wrong.

**Comment by joshan1120** [comment]
Any thoughts on how I can automate a SQL installation that requires that features? Pretty new to DSC :(

**Comment by forensicsguy20012004** [comment]
@joshan1120 ... That is a great question. So, first thoughts would be...start coding a modification to the resource(s) and then submit it is as a PR. I think essentially we are talking about one...maybe two resources that might need modification/re-code. If you are not into all that or cannot do that because of corporate policies the next best thing would be to see if you can reach out to a team member on xSQLServer and see if someone would be willing to "take up the cause." 

So you mentioned you are new to DSC but are you new to Powershell? If you are not new to Powershell, this should not be a big thing, just need to get more acquainted with DSC. If you are new to Powershell and DSC...now is a great time to learn some new skills. The xSQLServer project has some amazing Powershell and Dev folks and all of them, I think, would be more than happy to lend advice and support.

That is my advice, take it with a grain of salt.

**Comment by pmcevoy** [comment]
How is it possible that this bug is alive so long? surely an installation of SQLENGINE without Client Connectivity (CONN) is simply broken by deafult?  How can you connect to it or even configure Tcp using xSqlNetwork?  (Or am I misunderstanding what CONN gives you?)

**Comment by johlju** [comment]
@pmcevoy Together, as contributors (you among us), we are submitting issues, discussing issues, fixing bugs and adding enhancements. Everybody is doing a great job contributing, but there are still a lot of technical debt to cover. This bug will be resolved as soon as a contributor have time to take it on. 
If you want to help to fix this issue, you are more then welcome to do so. 😄 

You don't have to install CONN to connect to the server. I have actually never installed CONN on the server. And they are listed under Management tools in the link below.

>Connectivity Components
>Installs components for communication between clients and servers, and network libraries for DB-Library, ODBC, and OLE DB.
>https://msdn.microsoft.com/en-us/library/ms144275(v=sql.100).aspx

>Installs connectivity components.
https://msdn.microsoft.com/en-us/library/ms144259.aspx#Feature

I can't find a link that says what it actually installs and what it is used to.

**Comment by pmcevoy** [comment]
@johlju I sincerely apologise if my tone came across so bad - it really was not my intention to sound so entitled.  I absolutely value the work that all the contributors give to this (and other) OSS projects, and I really regret that my own work commitments prevent me from contributing more.  

At the moment, all I can do is try to submit as detailed issue as possible and try to research them (and in one or two cases even close the my issues when I realize they are dupes or a side effect of other issues (please see #379, #380 and #381).  I really don't intend to dump-and-run.

I find DSC as a whole incredibly satisfying and frustrating in equal measures.  Satisfying because managing 20 test VMs and replacing them every quarter has become a simple job.  Frustrating because the technology hides so much from you and is so impenetrable to diagnose when there are bugs in Resource definitions/implementations.  With something like sql server installation the edit-compile-test cycle is SO long, that frustration can bubble over.  Nevertheless, the xSqlServerSetup Resource is a damn sight better than the custom script Resource I had before, and workarounds using xSqlLogin and xSqlRole can be used to workaround the SQLSYSADMINS bug

I would like to help more if I can.  I only get to look at DSC once every few months, and if you can let me know how to locate the Feature guids used by the module to detect installed features (for 2012 CONN, BC and BOL) I will add them to this thread and that may help  a future maintainer.   Unfortunately we have not migrated to 2014/2016 yet, so will not be able to help there.

Many apologies again

**Comment by johlju** [comment]
@pmcevoy No worries, nobody took offence. It was a normal question like any other. 😄
I have seen the issues you have submitted, and be sure, they are as equally important contributions as any other contribution! Haven't had the time to respond though. I am thrilled that you comment on solutions and workarounds!

And you are right with the long time to test small changes in the configuration. I hoping we soon get integration tests, so that a user can run those against there environment and test all the resources. That together with the unit test I hope will catch even more bugs. But there are not unit test for all resources yet either. After those are done, we need to start looking at integration tests.

Regarding on how to detect CON, BC and BOL. What I would do would be to take a snapshopt of the registry, then install just CONN without anything else, make sure the minimum requirements is installed before taking the snapshot, then see what changed in the registry and see if that could be used to detect that it is installed.

Different approaches to detect installed features. There are no right or wrong, just those that works and are stable between SQL major versions, and are unique to that specific feature.

Thru SQL regsitry entries:
https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L112

Thru uninstall registry entries
https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L223

Thru installed regsitry entries
https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L276

**Comment by joshan1120** [comment]
Check this pull, sorry I haven't had time to complete the requests, but it does what you are asking for CONN, and BC and shows the reg key to do your tests against. I have been using that in house for a couple months now without any issues.

https://github.com/PowerShell/xSQLServer/pull/163

**Comment by johlju** [comment]
@joshan1120 yes that is correct, I forgot that you are already working on this. If you feel you won't have time to continue with it, then please make sure "Allow edits from maintainers" are turned on and I can see if I can get this one done. :)

**Comment by johlju** [comment]
@pmcevoy Would it be possible for you to try out this branch and see that it works for you? https://github.com/johlju/xSQLServer/tree/support-conn-and-bc

I'm just gonna write tests for this before I can merge it.

**Comment by pmcevoy** [comment]
@johlju  OK - it's taken a while to look at this this morning, mainly due to the fact that I am using a Pull server and updating modules used by DSC is a complicated set of musical chairs.  Normally I use Install-Module to get a module on to the Pull server, and then include it in the ModuleList for Publish-DSCModuleAndMof.  

For posterity, here is the process I did to roll-out the update to the module
- replace the MSFT_xSQLServerSetup folder in the Modules folder of the pull server
- re-xecute Publish-DSCModuleAndMof for my configuration, but ensure to include xSqlServer in the ModuleList
- on each client, I needed to remove the xSqlServer modules folder
- restart the client (in case for some reason the module was cached in the LCM)
- On each client, Update-DscConfiguration -Wait -Verbose to force config refresh

It appears that the xSqlServerSetup reports the following:

`
...
VERBOSE: [TESTEZE-BE67HAU]:  [[xSQLServerSetup]RDBMS] 2017-02-13_12-22-32: Client
Connectivity Tools feature detected
...
VERBOSE: [TESTEZE-BE67HAU]:  [[xSQLServerSetup]RDBMS] 2017-02-13_12-22-35: Features found:
'SQLENGINE,CONN,FULLTEXT,SSMS,ADV_SSMS'
...
`

So I'd say that appears to have worked for CONN  (and subsequent Configuration checks do not attempt to run the installer again).
