### ISSUE TITLE
Add "Dynamically determine port" parameter for xSQLAlias Resource

### ISSUE THREAD

**Issue by luigilink** [PowerShell/xSQLServer#146]
It's impossible to configure "Dynamically determine port" instead of default TcpPort 1433.
The parameter TCPPort with UInt16 type is not possible to configure Dynamically determine port, because the $tcpPort equal to '0', or it must be a 'null string'.

Fix in pull request #147 

BREAKING CHANGE:
The type of the parameter TCPPort has changed. It is now String Type.

**Comment by johlju** [comment]
Wouldn't it be more logical if we added a optional boolean parameter `UseDynamicPort` and left the TcpPort parameter as is? Then it wouldn't be a breaking change?
Want do you think?

**Comment by luigilink** [comment]
We can't keep TcpPort with the type UInt16, because when the parameter is "null" the value will be 0.
0 not working for UseDynamicPort, I tested it :(
Or the goal of this resource is to change a regedit key with type of String value.

**Comment by johlju** [comment]
My thought was that since TcpPort is not mandatory we could leave it as is (as a UInt16 type) because it don't have to be specified in the config file. Instead we could have a new optional parameter called `UseDynamicTcpPort` which defaults to `$false`. When `UseDynamicTcpPort` is set to `$true` the value in parameter `TcpPort` is ignored (if specified, or contains the default value), which results in the registry string without port as you proposed in your PR. So instead of the validation check `if (![System.String]::IsNullOrEmpty($TcpPort))` it would be something like `if (!$UseDynamicTcpPort)`.

My thought is that this would be better option than change the `TcpPort` parameter to a string type.

**Examples of config:**

Alias with specific port:
```
xSQLAlias myAlias
{
    Ensure = 'Present'
    Name = 'myAlias'
    ServerName = 'sqlhostalias.company.local'
    Protocol = 'TCP'
    TcpPort = 1433
}
```
Alias with dynamic port:
```
xSQLAlias myAlias
{
    Ensure = 'Present'
    Name = 'myAlias'
    ServerName = 'sqlhostalias.company.local'
    Protocol = 'TCP'
    UseDynamicTcpPort = $true
}
```

**Comment by luigilink** [comment]
You're right, it's a better solution.
I'll change the code. Thanks @johlju !

**Comment by luigilink** [comment]
It's done !

**Comment by johlju** [comment]
Awesome! I saw your commits. Impressed of the work you do!  It only here but in the other repositories!
I'm on a little mini vacation for two days so afraid it will take until end of the week for me to start the review, but I will review as soon as possible unless someone else beat me to it :smile:

**Comment by luigilink** [comment]
Thanks @johlju for your feedback !
