### ISSUE TITLE
xSQLServerSetup: Provision failed with non-enUS OS language

### ISSUE THREAD

**Issue by luigilink** [PowerShell/xSQLServer#153]
**Details of the scenario you try and problem that is occurring:**
Provision failed with xSQLServerSetup  in non-enUS.
xSQLServerSetup try to access to this file: ..\fr-FR\xSQLServer.strings.psd1, but this folder does not exist

**The DSC configuration that is using the resource:**
xSQLServerSetup 

**Version of the Operating System and PowerShell the DSC Target Node is running:**
- PowerShell Version: 5.0.10586.117
- OS Version : Windows 2012 R2 + French Language Pack

**Version of the DSC module you're using:** xSQLServer 2.0.0.0

**Comment by kwirkykat** [comment]
@luigilink This same issue was occurring in xPSDesiredStateConfiguration resources due to calls to Import-LocalizedData.

It looks like the actual resource isn't using Import-LocalizedData, but the [helper module](https://github.com/PowerShell/xSQLServer/blob/dev/xSQLServerHelper.psm1) is on lines 5 and 6.

As a workaround, you can either add a fr-FR folder with the required strings in French or you can just comment out the Import-LocalizedData lines in the helper module and create fake $LocalizedData and $USLocalizedData (not sure why this is here...) hashtables with the same strings as the en-US strings file instead.

You could also just copy the [Get-LocalizedData function](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/CommonResourceHelper.psm1#L113) from xPSDesiredStateConfiguration/PSDscResources since that is the correct way this should be written.

**Comment by johlju** [comment]
@luigilink Localization has been added for xSQLServerSetup and the helper functions (xSQLServerhelper). When the next release is released (in July I think), you should no longer get this issue. 

And if you would like to contribute the French localization strings that would be great 😄 

I will close this issue now. Thank you for reporting this!
