### ISSUE TITLE
Adding specific guidelines for contributing to xSQLServer

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#158]
I think we need to add some guidelines that are specific to xSQLServer. So far I have found the following specific guidelines that would help new contributors.
- Resource name should be prefixed with 'MSFT_xSQLServer'.
- Throwing an error should be done using `New-TerminatingError` (for localization).
- Writing verbose messages should be done using `New-VerboseMessage` (for localization).
- (soon, in PR) Writing warning should be done using `New-WarningMessage` (for localization).

I bet there are more we could add, this was just top of my head. If you know anything else that should be added, please comment.

Either we do a CONTRIBUTING.md in this module, or we start a wiki like @BrianFarnhill did in SharePointDsc.
https://github.com/PowerShell/SharePointDsc/wiki/Contributing%20to%20SharePointDsc

I am happy to take this on, if we agree this should be done.

@mbreakey3 @kwirkykat If we go the wiki way, is it okay to start a wiki? Are contributors (all users) allowed to edit wiki pages?
Seems there is not a (easy) way to PR into a wiki. Seems GitHub Pages is the way to got to be able to PR in changes. Have you looked at that yet?

**Comment by kwirkykat** [comment]
@johlju Thinking about this still. GitHub Pages looks cool...
This README is very long...

One tiny clarification:
All *mof-based* resources (with Get/Set/Test-TargetResource) should be prefixed with 'MSFT_xSQLServer'.
Any composite (with a Configuration) or class-based resources (though these add other complications...) should be prefixed with just 'xSQLServer'.

**Comment by BrianFarnhill** [comment]
@johlju So we have our own contributing guide for the extras that are above the standard guidelines, so sounds like you have a couple of things there that could fit that. As for mine being a wiki, that's something that has just been that way since waaaaaaaaaaaaaaay back in the day and I just haven't updated. For that document we probably should shift across to the CONTRIBUTING.md approach so others can submit PRs on that. Most of our wiki gets generated from content in the module anyway so it's all PR'able in that form, but something like that might be better for us to pull out of the wiki on this one rather than go down the pages from (I like the idea of keeping things in a single repo as much as possible, which is why I would take that approach). That's just my two cents on it though :)

**Comment by johlju** [comment]
I think we go with the CONTRIBUTING.md for the time being then. That can be migrated over to GitHub Pages, or something else, when we are so far along. 😄 

@kwirkykat I will make sure your clarification makes it in into the text. And also a link to the text about that in DscResource when it is merged.

@BrianFarnhill I think the documentation that is automatically updated in the Wiki is great approach. Would love to have that here too, I thought I while back I would check that out. I flagged the e-mail when I saw you merged it in... DscResource I think, and see what would take to make it work here. But haven't had time for that yet :/ Might require maintainer power too 😄

**Comment by BrianFarnhill** [comment]
@johlju Ping me an email if you need a hand getting any of it in :)

**Comment by johlju** [comment]
@BrianFarnhill Will do :)

**Comment by johlju** [comment]
Another specific guideline that we could add is how examples are placed. @luigilink started to incorporate a new way for this which I think that is a good idea. I think he got the idea from SharePointDsc resource as well. 

https://github.com/PowerShell/xSQLServer/tree/dev/Examples/Resources/xSQLServerRole

Under which each example (file name) is numbered
1-AddServerRole.ps1
2-RemoveServerRole.ps1

**Comment by johlju** [comment]
@luigilink Wouldn't it be easier to keep all folder names consistent with the prefix 'MSFT_'? Is it a reason for it to be named without the prefix?

@BrianFarnhill Maybe some automation used in SharePointDsc we need to take in account for this? Is the examples used in the integrations test in some way?

**Comment by johlju** [comment]
I added a text about helper functions as well. Anyone, please review the PR and comment. Or comment and add suggestions here if you don't want to load up Reviewable.

**Comment by johlju** [comment]
Yet another thing to add to the specific guideline. What SQL Server versions should we target? 

I would guess that we need to make the resource work for all still supported SQL Server versions that contains the functionality the resource targets. That would be SQL Server 2008 SP4 if we also target versions that are in extended support.

**Comment by BrianFarnhill** [comment]
@johlju The reason we don't use MSFT_ on the example folder names was because the examples directory was designed to be more "user friendly", so for example since a user never uses a resource called "MSFT_SPFarm" they use "SPFarm" the folders there line up to what the user would be actually using, not the internal name

**Comment by johlju** [comment]
@BrianFarnhill Thanks for clearing that up! Then we keep them the same way as the SharePointDsc repo.
