### ISSUE TITLE
Review additions from robwi repo

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/xSQLServer#169]
Additions have been made to this module in a separate repo:
[https://github.com/robwi/xSQLServer](https://github.com/robwi/xSQLServer)

HELP WANTED

If someone would like to review this work and incorporate changes back to the resource kit as a new PR, that would be a great project.

**Comment by johlju** [comment]
I have started to look at this code to see what changes you made.

**Comment by johlju** [comment]
No obvious changes in resources except xSQLServerSetup. Notable differences in xSQLServerSetup below. 

- Default values on parameters
 - `Features = "SQLENGINE"`
 - `$UpdateEnabled = "True"`
 - `$UpdateSource = ".\Updates"`

@mgreenegit there are changes in xPDT.xml. That .xml file is used in the exported function `GetxPDTVariable` from module xPDT.psm1. The exported function is not used by any resource in the module. I'm very interest in what scenario you are using this exported function. Could you be so kind to explain when you use this function? 
The reason I'm asking is because we are looking into removing the xPDT.psm1 module since it it gonna be obsolete with PR's currently proposed to the xSQLServer.

**Comment by robwi** [comment]
xPDT.psm1 and xPDT.xml are used across multiple DSC modules, and not all functions are used in all modules.

**Comment by johlju** [comment]
@robwi thanks for your comment. Maybe those changes @mgreenegit made in xPDT.xml would be more suitable in a repository that uses the `GetxPDTVariable` then?

@mgreenegit In my honest opinion there are no additions in you fork that would add value to this module. 
Of the default values in my previous comment, I thought at first that `$UpdateSource` could have benefited the xSQLServerSetup resource. But since the default value for the setup.exe is `'MU'` which means using Windows Update I don't see any need to change that behavior.

@mgreenegit please correct me if I'm wrong.

**Comment by mgreenegit** [comment]
@johlju thank you for taking the time to review.  If there is nothing to bring forward from the fork then I am definitely good with closing out the issue.  I would consider that a successful outcome.
