### ISSUE TITLE
Add more than 1 SQL Auth Account with xSqlServerLogin

### ISSUE THREAD

**Issue by joshan1120** [PowerShell/xSQLServer#170]
I am trying to add more than one SQL authentication account that have different passwords, but am encountering the following error.

_Resources have identical key properties but there are differences in the following non-key properties: 'LoginCredential'. Values 'System.Management.Automation.PSCredential' don't match values 'System.Management.Automation.PSCredential'. Please update these property values so that they are identical in both cases._

Am I doing something wrong, or is this truly a limitation? If it is and I were to try to update this to work with more than 1 login, any ideas where I would start?

**Comment by johlju** [comment]
The parameter `Name` should be set to the login name of the user. If the parameter `LoginType` is set to `SqlLogin` then you need to provide a password in the parameter `LoginCredential`. Please note that username in the `LoginCredential` is ignored. `LoginCredential` is only is only used to securely pass the password.

Since `Name` is a key, you should be able to add two SQL authentication logins. You do need to use version 2.0.0.0 of this module.

Does this answer your question?

**Comment by joshan1120** [comment]
Ya thanks, I think I got it going. I also built a loop so I only need one resource. testing it now.

foreach ($sqlAuthAccounts in $environmentNode.sqlUsers) {
				$sqlAuthAccounts
				$userPw = (Get-AzureKeyVaultSecret -VaultName $vaultName -Name $sqlAuthAccounts.keyVaultKey).SecretValue
				$userCreds = New-Object System.Management.Automation.PSCredential("NOTUSED", $userPw)

				xSQLServerLogin "SQlUserAccounts($sqlAuthAccounts)" {
					SQLServer = $env:COMPUTERNAME
					SQLInstanceName = $environmentNode.sqlInstanceName
					ensure = 'Present'
					LoginType = 'SqlLogin'
					Name = $sqlAuthAccounts.userName
					LoginCredential = $userCreds
					DependsOn = "[xSQLServerSetup]SqlServerSetup"

**Comment by johlju** [comment]
Looks good. Should work, right? But I do think you need
```
xSQLServerLogin "SQlUserAccounts($($sqlAuthAccounts.userName))" {
}
```

**Comment by joshan1120** [comment]
hah, you are fight :)
