### ISSUE TITLE
Instead of import helper module in each resource, can we add in psd1 file

### ISSUE THREAD

**Issue by luigilink** [PowerShell/xSQLServer#199]
Add module xSQLServer.Helper.psm1 in xSQLServer.psd1
Thanks to that, no need to import this module in each resource.

Suggested PR #198

**Comment by luigilink** [comment]
Is it possible to move also the module xPDT (psm1 + xml) in the folder modules. ?

**Comment by johlju** [comment]
I see no problem doing this since this is how SharePointDsc does it. But I think we need some restrictions.

* I would keep xPDT as-is, since that is gonna be obsolete soon enough. There is a PR currently that is gonna remove a lot of the functions in that module. Those functions who are left, if any, can be moved to 'xSQLServer.Helper.psm1'
* And I'm not comfortably doing this change for the resource that does not have tests. Please only do this change, for the time being, for those resource with tests.
* Also, all the help functions should be prefixed with something like 'SqlDsc', i.e `New-SqlDscVerboseMessage` so they do not conflict with other cmdlets on the node being configured, since we export the functions to the 'outside'.
* We need to change the specific guidelines (currently in PR) that this is the way new helper function are added, and resource does not have to import the module to access the helper functions.

**Comment by luigilink** [comment]
Totally agree, we keep xPDT on root folder for now.

**Comment by johlju** [comment]
If we change this for the resources without tests we cannot guarantee that we are not breaking anything, so I would not want to change this on resources without tests.
And all the helper functions should be prefixed with something like 'SqlDsc', i.e `New-SqlDscVerboseMessage`. Since this change would change every resource, we need tests as well for making sure we don't break anything.

I really would see this PR go thru. But in my opinion I think we should wait with this PR until we have test coverage on all resources. What do you think?

**Comment by luigilink** [comment]
Agree, we have to prioritize and today, one dscresrouce equal to one unit test.
So we can put this issue on hold until we have all tests.

**Comment by johlju** [comment]
No there is not an issue for that. We can use this issue for that change also I think.

**Comment by johlju** [comment]
@luigilink I don't see necessity to export the cmdlets. Issue PowerShell/xStorage#93 had to revert the same change because several modules used the same helper functions. And at the same time, all helper functions is used only by these resource and should not be exported.
The only benefit this would have is that there is no need to add an Import-Module to the resources for the helper module, which I don't see as a problem, to export the helper functions I see as a bigger potential problem.

I will close this issue and PR. But If this has any more benefit that I fail to see now, then please reopen this issue so we can discuss it. And we can reopen the PR too if that would be need.

Thanks!
