### ISSUE TITLE
xSQLServerHelper Unit Testing

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/xSQLServer#229]
**Details of the scenario you try and problem that is occurring:**
I fixed the bug identified in issue #187 and am finishing up writing my unit tests. I moved the Restart-SqlService function from the xSQLServerConfiguration module to the xSQLServerHelper module so it can be reused as needed.

Is there guidance in place for writing unit tests against functions that are contained in xSQLServerHelper?

**The DSC configuration that is using the resource (as detailed as possible):**
xSQLServerHelper

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
NA

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by johlju** [comment]
First, thank for contributing!! 😄  Awesome of you to fix that issue! Looking forward to see it merge.

There are no specific guidance on writing test for helper functions. But usually the tests for helper functions, if only used by a single resource, are tested within that resources tests. But that is not a hard rule. Writing a separate test file for those helper functions could do just fine as well.
Personally I like to limit the mocking to bare minimum so that the code in the helper functions is also tested at the same time at the Get-/Set- and Test-method. But that is not always possible. So a separate test for testing the helper functions is a good idea! 😄     

For the helper function Restart-SqlService there are already a test written which could be moved out to a separate test file.
See the test code for xSQLServerConfiguration here https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1#L288 

You must use this unit test template as the base for your tests. I has a framework to run the tests correctly in the AppVeyor build worker when you send in a pull request. 
https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

When running tests locally (Invoke-Pester) it will create a folder DscResource.Tests. This folder should not be sent in with the pull request. Make sure to add a .gitignore file to ignore this folder.
See https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#using-gitignore-to-exclude-files-andor-folders

You have test guidelines here
https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md

If you have any further questions just ask 😄

**Comment by randomnote1** [comment]
Thanks for the guidance!
