### ISSUE TITLE
xSQLServerSetup: Get-TargetResource does not detect clustered SSAS instances

### ISSUE THREAD

**Issue by nabrond** [PowerShell/xSQLServer#334]
**Details of the scenario you try and problem that is occurring:**
After PR #326 is merged, Get-TargetResource will not collection information about a clustered Analysis Services instance. Currently, only clustered SQL Server instances are supported.

**The DSC configuration that is using the resource (as detailed as possible):**
None.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Any

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by johlju** [comment]
If think this one got solve by PR #404. I can now install SSAS and Get-TargetResource successfully recognizes that analysis services is installed. Minor issues with the helper function Connect-SQLAnalysis that was submitted in issue #436 (work in progress).

Since the Get-TargetResource successfully detects SSAS instance in a cluster I will close this issue.
