### ISSUE TITLE
How to use configurationfile.ini in xSQLServerSetup

### ISSUE THREAD

**Issue by Purclot** [PowerShell/xSQLServer#491]
**Details of the scenario you try and problem that is occurring:**
Hi folks,
how can I use a configurationfile.ini using xSQLServerSetup? I must admin: I'm still having hard time to get the "big picture" which file and how configured do I need to install the SQL-Server? Only, let's say the file: InstallDefaultInstanceSingleServer.ps1? Thanks for your help.
Purclot Avignon
**The DSC configuration that is using the resource (as detailed as possible):**
xSQLServer
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2012 R, PS Ver. 5
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

**Comment by randomnote1** [comment]
Hi @Purclot, currently the INI file is not supported with xSQLServer. Take a look at issue #377 for some details around the conversation.

I'll let @johlju comment on the example configuration.

**Comment by Purclot** [comment]
hi Dan, thanks for your fast response. I'd really love to participate on this project, but I still don't get the "big picture" about the module xSQLServer. Do we have some simple docs describing the stuff?
Thanks for your help
Purclot

**Comment by randomnote1** [comment]
The documentation is something we've been discussing how to handle since we rely on other components and resources in DSC. Right now the documentation is the README.md file that is available on the project home page.

The purpose of managing SQL with DSC is to ensure consistency across any number of servers and to ensure the state of the instance, server, databases, etc. doesn't drift.

What's your experience level with DSC? Have you tinkered with any of the basic tutorials?

**Comment by Purclot** [comment]
hi Dan,
my DSC-experience is very low, I've started with some basic tutorials (thanks for any advice!), my company  pushes me and the need for a SQL Server DSC is a huge topic, means for me: jump in! So thanks for any advice and hints how to start with DSC, I hope then to collaborate and help later!
Purclot

**Comment by johlju** [comment]
@Purclot Thanks for asking the question! I bet more people than you are wondering the same.

As @randomnote1 said, currently there is no step-by-step on how to use this resource. Unfortunately, at this stage, the documentation assumes that the user has a knowledge in the workings of LCM and DSC.
It is not as easy as download the module an run the InstallDefaultInstanceSingleServer.ps1 script. But I guess you figured that out already since you are asking. 😄 

If you want to learn how LCM and DSC works I would suggest reading this book https://leanpub.com/the-dsc-book. It do assume that you have a knowledge of PowerShell.

After that you could start (in simple terms) by deploying a VM, setting LCM into push mode, creating a configuration file that contains for example .Net Framework and push that to a client. But pushing SQL Server in an environment (for examples using the configuration in the example InstallDefaultInstanceSingleServer.ps1) you need more, like certificate to encrypt the configuration (when using passwords for accounts) and on each server you need to have the same certificate to encrypt the passwords.
If you gonna pull the configuration then you need a pull server on top of all that. :)
All this is explained in the book I mentioned earlier. But it does not go into how to use the xSQLServer resources. But I think, when you read that book you have a much bigger understanding on what you need to do to get a test and production environment running using DSC.

I hoped this help.

**Comment by Purclot** [comment]
hi Johan,
thanks for your answer, it explains a lot. I hoped it would be (a bit) easier, but it's always the same with a new technology! The DSC seems to be a cool thing, my company is pushing me into it, so let's do it. I hope to get the grip, if so, maybe I could help you and other contributors!
Purclot

**Comment by johlju** [comment]
@Purclot You are more than welcome to contribute in any way you can! You already started by submitting an question (issue) 😄 

Can we close this issue at this time?

**Comment by Purclot** [comment]
yes, please!
