### ISSUE TITLE
xSQLServerSetup: SetupCredential no longer used?

### ISSUE THREAD

**Issue by xilience** [PowerShell/xSQLServer#674]
Running a SQL 2012 install test with updated DSC Resources. 

Used same parameters earlier in the day with release 7.1 of the xSQLServer Resource. However, when running with commit 67bf54a, I get an error when creating the mof.
"SetupCredential is not valid. Valid parameters are..." Followed by the list of all possible parameters. 

I commented out the SetupCredential parameter and the configuration worked without issue. So is this parameter no longer used?

**Comment by johlju** [comment]
That parameter was removed since it did not fill any purpose any longer. 

Version 8.0 will released in a few days with this breaking change. Please see he change log for more information about all breaking changes for v8.0. :smile:

https://github.com/PowerShell/xSQLServer/blob/dev/CHANGELOG.md

I do see that xSQLServerSetup is split to two paces in the changelog. I will make sure to fix that tomorrow.

**Comment by xilience** [comment]
Thanks!
