### ISSUE TITLE
DSCFCISqlBuild.ps1 is outdated

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/xSQLServer#717]
Hey, just thought I'd point out the example [here](https://github.com/PowerShell/xSQLServer/blob/dev/Examples/DSCFCISqlBuild.ps1) is still using `xSQLServerFailoverClusterSetup`, which as far as I can tell doesn't exist anymore.

**Comment by johlju** [comment]
Yes, all the examples in the root of /Examples should be rewritten, because they reference resources that no longer exist or has been been updated with breaking changes.  We had a discussion about that here https://github.com/PowerShell/xSQLServer/issues/462 and my thought was that I would have time to fix this during the month that went by. But other stuff needed to be done 
I'm looking at splitting these examples between xSQLServer and xFailOverCluster. Help is welcomed. :)

**Comment by johlju** [comment]
Closing this and tracking this in issue #462.
