### ISSUE TITLE
xSQLServerRole: Returns an error when calling Get-DscConfiguration

### ISSUE THREAD

**Issue by seizste** [PowerShell/xSQLServer#790]
xSQLServerRole DscRessource returns an error when running Get-DscConfiguration

Get-DscConfiguration : GetConfiguration did not succeed.

Event Log give some more details

Message Unable to cast object of type 'System.String' to type 'System.Collections.IList'.
Parameter name: value

Implicitly casting Return Value to a String Array fixes this issue, but there's probably a better way to do this.

    $returnValue = @{
        Ensure           = $ensure
        Members          = [System.String[]]$membersInRole
        MembersToInclude = [System.String[]]$MembersToInclude
        MembersToExclude = [System.String[]]$MembersToExclude
        ServerRoleName   = $ServerRoleName
        SQLServer        = $SQLServer
        SQLInstanceName  = $SQLInstanceName
    }

**Comment by johlju** [comment]
Does this only happen when there is only one member in the group? If so, then `$membersInRole` is cast to a `[System.String]` instead of `[System.String[]]`.
Because the other two are already typed to arrays in the parameter declaration.

If so it should suffice to make sure this line always cast to a `[System.String[]]`.

https://github.com/PowerShell/xSQLServer/blob/375ead160420c2f9cb262609a825370887b7fcee/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L70

**Comment by seizste** [comment]
Still get an error even if adding multiple Groups to MembersToInclude . Configuration is applied but Get-DscConfiguration fails with same error.
