### ISSUE TITLE
xSQLServerNetwork: TcpDynamicPorts parameter is using blank string instead of being a System.Boolean

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/xSQLServer#855]
Question: why is the TCPDynamicPorts parameter defined in the following way:

[Parameter()]
[ValidateSet('0', '')]
[System.String]
$TcpDynamicPorts,

Why set this as a string instead of a Boolean? Thanks

**Comment by randomnote1** [comment]
I imagine because zero (0) indicates dynamic ports are in use, and an empty string indicates a static port is in use when configuring this in SQL Configuration Manager.

Reference: [Configure a Server to Listen on a Specific TCP Port](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port)

I think your point is valid though. It would seem more consistent with other DSC resources to use a Boolean operator to indicate the status.

**Comment by johlju** [comment]
When this resource was used to

**Comment by johlju** [comment]
When tests was created for this resource it was determined that it did not handle setting back to a static port. To resolve that at that time, without making a breaking, the `''` was added and issue #534 was opened, which agrees this should be a `System.Boolean`.

@NikCharlebois If you like to help resolve this, please let me know in the other issue, and I lable that issue as in progress. Closing this since we are tracking this in the other issue.
